package exceptionhandling;
import java.util.Scanner;
public class Exception1 {
	public static void main(String[]args) {
	}
		public static int addnumber(int a , int b) {
			return a/b;
		try {
			Scanner obj = new Scanner(System.in);
		System.out.println(10/2);
		}catch(Exception e) {
			System.out.println("dont divide with 2");
		}
	}

}
		